### ISSUE TITLE
How to use the native target on Linux?

### ISSUE THREAD

**Issue by probonopd** [AnotherJohnH/picoX7#10]
How to get MIDI input into the native target on Linux and/or sound out of it?

```
./picoX7_NATIVE

Program  : picoX7 (native)
Author   : Copyright (c) 2023 John D. Haughton
Version  : 0.18
Commit   : 6381560b020c1a3617568663ccafd5c57f9183a7
Built    : 18:41:18 Sep  9 2024
Compiler : 9.4.0

# 001 NAME BRASS   1  ALG 22 FBK 7 SYNC on  PMS 3 TRN 0
LFO WAV sin SPD 37 DLY 00 PMD 05 AMD 00 SYNC off
OP AMS FREQ    DET R1 R2 R3 R4  L1 L2 L3 L4  BPT   CURVE    DEPTH RTE OUT KVS 
6   0  R  1.00  0  49 99 28 68  98 98 91 00  39  -exp -exp  54 50  4   82  2
5   0  R  1.00  1  77 36 41 71  99 98 98 00  39  +lin +lin  00 00  0   98  2
4   0  R  1.00  0  77 36 41 71  99 98 98 00  39  +lin +lin  00 00  0   99  2
3   0  R  1.00 -2  77 76 82 71  99 98 98 00  39  +lin +lin  00 00  0   99  2
2   0  R  0.50  7  62 51 29 71  82 95 96 00  27  +lin -exp  00 07  0   86  0
1   0  R  0.50  7  72 76 99 71  99 88 96 00  39  +lin +lin  00 14  0   98  0
PITCH EG           84 95 95 60  50 50 50 50 
```

When I play notes on an attached MIDI controller (keyboard), I hear no sound and the output on the screen does not change.
When I do `sudo cat /dev/midi3` and press some keys on the keyboard, I do see activity there.

How to analyze/debug this?

**Comment by AnotherJohnH** [comment]
Ouch, sorry, I should use Linux more often! If you look in `Platform/PLT/Linux/CMakeLists.txt` you will find that the MIDI modules are stubs. e.g. compare with the `macOS` sub-directory which has actual implementations.

I have a Linux VM. Be happy to have a quick look.

**Comment by AnotherJohnH** [comment]
This [patch](https://github.com/AnotherJohnH/picoX7/commit/58a0eb7a6a6f1b0d9cf4a139e7179419651d6804) should help get something working. There seems to be some significant latency. Maybe it's because I used a Linux VM or maybe it's my misuse of the Linux API?
